# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(default=-1)),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(unique=True)),
                ('themoviedb', models.IntegerField(null=True)),
                ('imdb', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(max_length=7)),
                ('rottentomatoes', models.IntegerField(null=True)),
                ('metacritic', models.CharField(max_length=200, null=True)),
                ('common_sense_media', models.CharField(max_length=200, null=True)),
                ('poster', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=2500, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date', models.IntegerField(null=True)),
                ('netflix', models.CharField(blank=True, max_length=200, null=True)),
                ('netflix_available', models.BooleanField(default=False)),
                ('amazon', models.CharField(blank=True, max_length=200, null=True)),
                ('amazon_available', models.BooleanField(default=False)),
                ('hulu', models.CharField(blank=True, max_length=200, null=True)),
                ('hulu_available', models.BooleanField(default=False)),
                ('trailer', models.CharField(max_length=200, null=True)),
                ('tmdb_get', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(to='movierec.Genre')),
                ('keywords', models.ManyToManyField(to='movierec.Keyword')),
                ('languages', models.ManyToManyField(to='movierec.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(default=-1)),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(to='movierec.Person'),
        ),
    ]
