# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20170419_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='god', max_length=25),
            preserve_default=False,
        ),
    ]
