# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0001_initial'),
        ('useraccount', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_genres',
            field=models.ManyToManyField(related_name='disliked_genres', to='movierec.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_genres',
            field=models.ManyToManyField(related_name='liked_genres', to='movierec.Genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_list',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disliked_movies',
            field=models.ManyToManyField(related_name='disliked_movies', to='movierec.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_movies',
            field=models.ManyToManyField(related_name='liked_movies', to='movierec.Movie'),
        ),
    ]
