# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('themoviedb', models.IntegerField()),
                ('imdb', models.IntegerField()),
                ('rating', models.CharField(max_length=7)),
                ('rottentomatoes', models.IntegerField()),
                ('wikipedia_id', models.IntegerField()),
                ('metacritic', models.CharField(max_length=200)),
                ('common_sense_media', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('date', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movierec.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movierec.Genre'),
        ),
    ]
