# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(max_length=200),
        ),
    ]
