# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0002_auto_20170415_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='identifier',
            field=models.IntegerField(unique=True),
        ),
    ]
