# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierec', '0003_auto_20170416_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amazon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='hulu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
