# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3_whattowatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show_amazon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_hulu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_netflix',
            field=models.BooleanField(default=False),
        ),
    ]
